// Generated by tools/generate-i18n-types.ts. Do not edit.
// Run `pnpm i18n:types` after changing a dictionary.

export type MessageKey =
	| 'a11y.direction.asc'
	| 'a11y.direction.desc'
	| 'a11y.localeSwitcher'
	| 'a11y.skipToContent'
	| 'a11y.sortColumn'
	| 'a11y.tableSummary'
	| 'a11y.themeToggle'
	| 'blog.empty'
	| 'blog.readMore'
	| 'blog.readingTime'
	| 'blog.title'
	| 'channel.email'
	| 'channel.push'
	| 'channel.sms'
	| 'channel.social'
	| 'channel.web'
	| 'common.cancel'
	| 'common.error'
	| 'common.loading'
	| 'common.retry'
	| 'common.save'
	| 'dashboard.canEdit'
	| 'dashboard.items.column.budget'
	| 'dashboard.items.column.channel'
	| 'dashboard.items.column.ctr'
	| 'dashboard.items.column.name'
	| 'dashboard.items.column.owner'
	| 'dashboard.items.column.spent'
	| 'dashboard.items.column.status'
	| 'dashboard.items.column.updated'
	| 'dashboard.items.empty'
	| 'dashboard.items.emptyBody'
	| 'dashboard.items.filters.channel'
	| 'dashboard.items.filters.options'
	| 'dashboard.items.filters.placeholder'
	| 'dashboard.items.filters.status'
	| 'dashboard.items.filters.tags'
	| 'dashboard.items.filtersFailed.body'
	| 'dashboard.items.filtersFailed.title'
	| 'dashboard.items.new'
	| 'dashboard.items.noMatches.body'
	| 'dashboard.items.noMatches.title'
	| 'dashboard.items.noStream'
	| 'dashboard.items.rowsFailed.body'
	| 'dashboard.items.rowsFailed.title'
	| 'dashboard.items.search'
	| 'dashboard.items.title'
	| 'dashboard.readOnly'
	| 'dashboard.role'
	| 'dashboard.subtitle'
	| 'dashboard.title'
	| 'dashboard.welcome'
	| 'error.404.body'
	| 'error.404.cta'
	| 'error.404.title'
	| 'error.500.body'
	| 'error.500.cta'
	| 'error.500.title'
	| 'footer.copy'
	| 'home.features.accessibility.body'
	| 'home.features.accessibility.title'
	| 'home.features.dx.body'
	| 'home.features.dx.title'
	| 'home.features.performance.body'
	| 'home.features.performance.title'
	| 'home.features.title'
	| 'home.hero.cta'
	| 'home.hero.subtitle'
	| 'home.hero.title'
	| 'login.demo.password'
	| 'login.demo.title'
	| 'login.demo.use'
	| 'login.email'
	| 'login.error'
	| 'login.error.email'
	| 'login.error.password'
	| 'login.password'
	| 'login.required'
	| 'login.signedInAs'
	| 'login.submit'
	| 'login.submitting'
	| 'login.subtitle'
	| 'login.title'
	| 'nav.blog'
	| 'nav.dashboard'
	| 'nav.home'
	| 'nav.login'
	| 'nav.logout'
	| 'nav.pricing'
	| 'nav.search'
	| 'pagination.next'
	| 'pagination.previous'
	| 'pagination.showing'
	| 'pricing.cta'
	| 'pricing.perMonth'
	| 'pricing.subtitle'
	| 'pricing.tier.scale'
	| 'pricing.tier.starter'
	| 'pricing.tier.team'
	| 'pricing.title'
	| 'role.admin'
	| 'role.editor'
	| 'role.viewer'
	| 'search.filters.clear'
	| 'search.filters.tagOption'
	| 'search.filters.tags'
	| 'search.noResults'
	| 'search.placeholder'
	| 'search.prompt'
	| 'search.results'
	| 'search.results.filtered'
	| 'search.sort.label'
	| 'search.sort.newest'
	| 'search.sort.oldest'
	| 'search.sort.title'
	| 'search.submit'
	| 'social.subtitle'
	| 'social.title'
	| 'status.active'
	| 'status.archived'
	| 'status.completed'
	| 'status.draft'
	| 'status.paused'
	| 'status.scheduled'
	| 'table.budget.edit'
	| 'table.budget.forbidden'
	| 'table.budget.invalid'
	| 'table.budget.invalidToast'
	| 'table.budget.label'
	| 'table.budget.missing'
	| 'table.budget.required'
	| 'table.budget.saved'
	| 'table.budget.signedOut'
	| 'table.budget.unavailable'
	| 'table.cancel'
	| 'table.conflict.dismiss'
	| 'table.conflict.mine'
	| 'table.conflict.overwrite'
	| 'table.conflict.theirs'
	| 'table.conflict.title'
	| 'table.save'
	| 'table.saving';

export const messageKeys: readonly MessageKey[] = [
	'a11y.direction.asc',
	'a11y.direction.desc',
	'a11y.localeSwitcher',
	'a11y.skipToContent',
	'a11y.sortColumn',
	'a11y.tableSummary',
	'a11y.themeToggle',
	'blog.empty',
	'blog.readMore',
	'blog.readingTime',
	'blog.title',
	'channel.email',
	'channel.push',
	'channel.sms',
	'channel.social',
	'channel.web',
	'common.cancel',
	'common.error',
	'common.loading',
	'common.retry',
	'common.save',
	'dashboard.canEdit',
	'dashboard.items.column.budget',
	'dashboard.items.column.channel',
	'dashboard.items.column.ctr',
	'dashboard.items.column.name',
	'dashboard.items.column.owner',
	'dashboard.items.column.spent',
	'dashboard.items.column.status',
	'dashboard.items.column.updated',
	'dashboard.items.empty',
	'dashboard.items.emptyBody',
	'dashboard.items.filters.channel',
	'dashboard.items.filters.options',
	'dashboard.items.filters.placeholder',
	'dashboard.items.filters.status',
	'dashboard.items.filters.tags',
	'dashboard.items.filtersFailed.body',
	'dashboard.items.filtersFailed.title',
	'dashboard.items.new',
	'dashboard.items.noMatches.body',
	'dashboard.items.noMatches.title',
	'dashboard.items.noStream',
	'dashboard.items.rowsFailed.body',
	'dashboard.items.rowsFailed.title',
	'dashboard.items.search',
	'dashboard.items.title',
	'dashboard.readOnly',
	'dashboard.role',
	'dashboard.subtitle',
	'dashboard.title',
	'dashboard.welcome',
	'error.404.body',
	'error.404.cta',
	'error.404.title',
	'error.500.body',
	'error.500.cta',
	'error.500.title',
	'footer.copy',
	'home.features.accessibility.body',
	'home.features.accessibility.title',
	'home.features.dx.body',
	'home.features.dx.title',
	'home.features.performance.body',
	'home.features.performance.title',
	'home.features.title',
	'home.hero.cta',
	'home.hero.subtitle',
	'home.hero.title',
	'login.demo.password',
	'login.demo.title',
	'login.demo.use',
	'login.email',
	'login.error',
	'login.error.email',
	'login.error.password',
	'login.password',
	'login.required',
	'login.signedInAs',
	'login.submit',
	'login.submitting',
	'login.subtitle',
	'login.title',
	'nav.blog',
	'nav.dashboard',
	'nav.home',
	'nav.login',
	'nav.logout',
	'nav.pricing',
	'nav.search',
	'pagination.next',
	'pagination.previous',
	'pagination.showing',
	'pricing.cta',
	'pricing.perMonth',
	'pricing.subtitle',
	'pricing.tier.scale',
	'pricing.tier.starter',
	'pricing.tier.team',
	'pricing.title',
	'role.admin',
	'role.editor',
	'role.viewer',
	'search.filters.clear',
	'search.filters.tagOption',
	'search.filters.tags',
	'search.noResults',
	'search.placeholder',
	'search.prompt',
	'search.results',
	'search.results.filtered',
	'search.sort.label',
	'search.sort.newest',
	'search.sort.oldest',
	'search.sort.title',
	'search.submit',
	'social.subtitle',
	'social.title',
	'status.active',
	'status.archived',
	'status.completed',
	'status.draft',
	'status.paused',
	'status.scheduled',
	'table.budget.edit',
	'table.budget.forbidden',
	'table.budget.invalid',
	'table.budget.invalidToast',
	'table.budget.label',
	'table.budget.missing',
	'table.budget.required',
	'table.budget.saved',
	'table.budget.signedOut',
	'table.budget.unavailable',
	'table.cancel',
	'table.conflict.dismiss',
	'table.conflict.mine',
	'table.conflict.overwrite',
	'table.conflict.theirs',
	'table.conflict.title',
	'table.save',
	'table.saving'
];
