/**
 * Emits the message-key union from the English dictionary and verifies that
 * German matches it exactly.
 *
 *   node tools/generate-i18n-types.ts           # write the generated file
 *   node tools/generate-i18n-types.ts --check   # fail if stale or out of parity
 *
 * The union is what makes t('nav.blga') a compile error instead of a blank spot
 * on the page, and the parity check is what stops translations drifting apart
 * once someone adds a key in a hurry.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);

const sources = {
	en: ['mocks/i18n.en.json', 'src/lib/i18n/extensions.en.json'],
	de: ['mocks/i18n.de.json', 'src/lib/i18n/extensions.de.json']
} as const;

const output = 'src/lib/i18n/keys.generated.ts';

function readDictionary(paths: readonly string[]): Record<string, string> {
	const merged: Record<string, string> = {};

	for (const path of paths) {
		const contents = JSON.parse(readFileSync(fileURLToPath(new URL(path, root)), 'utf8')) as Record<
			string,
			string
		>;

		for (const [key, value] of Object.entries(contents)) {
			if (key in merged) {
				throw new Error(
					`Duplicate key "${key}" in ${path}: an extension may not shadow a provided key`
				);
			}

			merged[key] = value;
		}
	}

	return merged;
}

function placeholders(value: string): string[] {
	return [...value.matchAll(/\{(\w+)\}/g)].map((match) => match[1]).sort();
}

function render(keys: readonly string[]): string {
	const union = keys.map((key) => `\t| '${key}'`).join('\n');

	return `// Generated by tools/generate-i18n-types.ts. Do not edit.
// Run \`pnpm i18n:types\` after changing a dictionary.

export type MessageKey =
${union};

export const messageKeys: readonly MessageKey[] = [
${keys.map((key) => `\t'${key}'`).join(',\n')}
];
`;
}

const en = readDictionary(sources.en);
const de = readDictionary(sources.de);
const keys = Object.keys(en).sort();

const problems: string[] = [];

for (const key of keys) {
	if (!(key in de)) {
		problems.push(`de is missing "${key}"`);
		continue;
	}

	const expected = placeholders(en[key]);
	const actual = placeholders(de[key]);

	if (expected.join() !== actual.join()) {
		problems.push(
			`"${key}" interpolates {${expected.join('}, {')}} in en but {${actual.join('}, {')}} in de`
		);
	}
}

for (const key of Object.keys(de)) {
	if (!(key in en)) {
		problems.push(`de has an extra key "${key}"`);
	}
}

if (problems.length > 0) {
	console.error(
		`i18n dictionaries are out of parity:\n${problems.map((p) => `  - ${p}`).join('\n')}`
	);
	process.exit(1);
}

const target = fileURLToPath(new URL(output, root));
const generated = render(keys);

if (process.argv.includes('--check')) {
	const current = (() => {
		try {
			return readFileSync(target, 'utf8');
		} catch {
			return '';
		}
	})();

	if (current !== generated) {
		console.error(`${output} is stale. Run \`pnpm i18n:types\` and commit the result.`);
		process.exit(1);
	}

	console.log(`i18n: ${keys.length} keys, en and de in parity, generated types up to date`);
} else {
	writeFileSync(target, generated);
	console.log(`i18n: wrote ${keys.length} keys to ${output}`);
}
